### ISSUE TITLE
Space character is inputted as NaN while inputting as integer.

### ISSUE THREAD

**Issue by razetime** [8Dion8/8Dion8.github.io#1]
In https://8dion8.github.io/?code=%40%3B.&input=%20%20%20%20 ,

Theres a problem where the @ function inputs spaces as NaN instead of 0.

**Comment by 8Dion8** [comment]
Problem is with the `isNaN()` function, which should return `false` only when the argument is a number. For some reason it also returns `false` for spaces. Should be fixed now, although there may be other characters do that, as all I've done was introduced a special case for spaces.
