### ISSUE TITLE
Strange copy paste bug?

### ISSUE THREAD

**Issue by razetime** [8Dion8/8Dion8.github.io#4]
character count increases by a high value on copypaste.
![MAWPbug1](https://user-images.githubusercontent.com/11015319/90092281-1fd93800-dd46-11ea-8767-e3856ab53f0d.gif)

**Comment by 8Dion8** [comment]
I think i know what the issue is, although, to be sure, could you see what the console says when you paste it in? It should say two things like "code before formatting" and "code after formatting", although I might have left some stray console.log statements elsewhere

**Comment by razetime** [comment]
byte count seems to be fine now for the same text. I'll leave this open just in case there's any other instance.

**Comment by 8Dion8** [comment]
The issue was that I was using a <span contenteditable> for the input, and that, for some reason, copied some random html with it. Now I switched to a textarea, so should be no more problems there

**Comment by razetime** [comment]
@ operator works without fuss now.

**Comment by razetime** [comment]
no issues with byte count right now.
