### ISSUE TITLE
`@` symbol does not show input , and prevents rest of program from executing

### ISSUE THREAD

**Issue by razetime** [8Dion8/8Dion8.github.io#5]
![MAWPbug2](https://user-images.githubusercontent.com/11015319/90305724-f43f8480-dee2-11ea-845e-92f2bbf680d3.gif)
Seems to work and not work under random circumstances. Will put up more info on this.

**Comment by 8Dion8** [comment]
Does the dev console show any errors?

**Comment by razetime** [comment]
I think changing to textarea fixed this problem as well. No serious console errors.
